-- Stores one row per employee per pay run for payslip generation and YTD totals.
-- Created by modPayroll::init() — do not run manually.

CREATE TABLE IF NOT EXISTS llx_payroll_payrun_line (
    rowid            INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fk_salary        INT           NULL,
    fk_user          INT           NOT NULL,
    entity           INT           NOT NULL DEFAULT 1,
    pay_period_start DATE          NOT NULL,
    pay_period_end   DATE          NOT NULL,
    pay_date         DATE          NOT NULL,
    fy               VARCHAR(10)   NOT NULL DEFAULT '',
    is_salary        TINYINT       NOT NULL DEFAULT 0,
    ord_hrs          DECIMAL(8,2)  NOT NULL DEFAULT 0,
    ord_rate         DECIMAL(12,4) NOT NULL DEFAULT 0,
    ot1_hrs          DECIMAL(8,2)  NOT NULL DEFAULT 0,
    ot1_mult         DECIMAL(5,2)  NOT NULL DEFAULT 1.50,
    ot2_hrs          DECIMAL(8,2)  NOT NULL DEFAULT 0,
    ot2_mult         DECIMAL(5,2)  NOT NULL DEFAULT 2.00,
    salary_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
    al_hrs           DECIMAL(8,2)  NOT NULL DEFAULT 0,
    sick_hrs         DECIMAL(8,2)  NOT NULL DEFAULT 0,
    bere_hrs         DECIMAL(8,2)  NOT NULL DEFAULT 0,
    gross            DECIMAL(12,2) NOT NULL DEFAULT 0,
    net              DECIMAL(12,2) NOT NULL DEFAULT 0,
    payg             DECIMAL(12,2) NOT NULL DEFAULT 0,
    super_amount         DECIMAL(12,2) NOT NULL DEFAULT 0,
    super_fund           VARCHAR(255)  NULL,
    super_fund_usi       VARCHAR(50)   NULL,
    super_member_number  VARCHAR(50)   NULL,
    bal_annual_after     DECIMAL(10,2) NULL,
    bal_sick_after   DECIMAL(10,2) NULL,
    deductions_json  TEXT          NULL,
    additions_json   TEXT          NULL,
    leave_note       VARCHAR(255)  NULL,
    date_created     DATETIME      NULL,
    KEY idx_prl_user   (fk_user, entity),
    KEY idx_prl_salary (fk_salary),
    KEY idx_prl_fy     (fk_user, entity, fy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
